export interface User {
    client: any,
    created_at: number,
    customs?: any,
    email: string,
    fullName: string,
    id: number,
    phone: string,
    photo_profile: any ,
    railyard?: any ,
    role: any ,
    token: string,
    updated_at: number,
    user_type: any,
    image_source: string,
}
